import localFont from 'next/font/local';
import {Galada,Assistant, Manrope} from "next/font/google"
import "./globals.css";

const crisman = Manrope({
  subsets:['latin'],
    weight:['400','700','600'],
  variable:'--font-crisman'
})

  const assistant = Assistant({
    subsets:['latin'],
    weight:'400',
    variable:'--font-assistant'
  })

const galada = Galada({
  subsets:['latin'],
  weight:'400',
  display: 'swap',
  variable:'--font-galada'
})

export const metadata = {
  title: "Youman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`dark ${crisman.variable} ${galada.variable} ${assistant.variable}`}>
      <body className="dark:bg-black font-assistant">{children}</body>
    </html>
  );
}
