
import { Manrope} from "next/font/google"
import "./globals.css";
import Footer from '@/components/Footer';

const crisman = Manrope({
  subsets:['latin'],
    weight:['400','700','600','800'],
  variable:'--font-crisman'
})



export const metadata = {
  title: "Youman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`light ${crisman.variable}  `}>
      <body className="dark:bg-black bg-[rgb(248 248 248)] font-crisman ">
        <section className="min-h-[100vh]">
        {children}
        </section>
      
      
      <Footer/>
      </body>
      
    </html>
  );
}
